[project]
name = "datashield-mcp"
version = "0.1.0"
description = "A MCP server to interact with DataSHIELD"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datashield>=0.3.0",
    "datashield-opal>=0.2.0",
    "mcp[cli]>=1.26.0",
    "matplotlib>=3.10.8",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.10.0",
]

[project.scripts]
datashield-mcp = "datashield_mcp.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/datashield_mcp"]

[tool.hatch.metadata]
allow-direct-references = true